---
title: "Playoff optimization"
author: "Ben Baumer"
date: "August 31, 2017"
output: html_document
---

## Load Data

```{r}
library(tidyverse)
library(tourneyr)

best_teams <- function(data, k = 8) {
  data %>%
    arrange(desc(mean_theta)) %>%
    head(k)
}
```


## Simulations

```{r}
sim_data <- bigfour_end %>%
#  filter(season == 10) %>%
#  filter(sport == "nba", season == 10) %>%
  group_by(sport, season) %>%
  do(best_teams(., k = 16))

# should be around 46%
long_run_prob(spurs_bulls, n = 1000)
long_run_prob(spurs_bulls, n = 1000, series_length = 7)
# should be nearly certain
long_run_prob(spurs_bulls, n = 1000, series_length = 99)

one_simulation(spurs_bulls)

sim_data %>% 
  do(one_simulation(., series_length = 7))
```

```{r 7-games, eval=TRUE}
# takes a few minutes
res <- sim_data %>%
  group_by(sport, season) %>%
  do(many_simulations(., n = 1000, series_length = 7))
save(res, file = "../data/res.rda", compress = "xz")
``` 
  
```{r}
res %>%
  group_by(sport, seed) %>%
  summarize(N = n(), mean_finish = mean(finish), wins = sum(finish == 1))

res %>% 
  filter(sport == "nba", season == 10, seed == 1) %>% 
  group_by(finish) %>% 
  summarize(N = n())

res %>%
  group_by(sport) %>%
  summarize(cor(seed, finish))
```

```{r}
res_grouped <- res %>%
  group_by(sport, seed) %>%
  summarize(mean_finish = mean(finish)) %>%
  mutate(predestination_finish = ceiling(log2(seed)) + 1)

parity <- res_grouped %>%
  summarize(parity_finish = mean(predestination_finish)) 

res_grouped <- res_grouped %>%
  inner_join(parity, by = "sport") %>%
  mutate(SSM = (mean_finish - parity_finish)^2,
         SST = (predestination_finish - parity_finish)^2,
         weight = 17 - seed)

labels <- parity %>%
  # hack for labels
  mutate(seed = 15, finish = 3.5, label = "perfect\nparity")

labels2 <- labels %>%
  mutate(seed = 2, finish = 1, label = "predestination")

r_squared <- res_grouped %>%
  group_by(sport) %>%
  summarize(r_squared = sum(SSM) / sum(SST),
            weighted_r_squared = sum(weight * SSM) / sum(weight * SST))

ggplot(res, aes(x = seed, y = finish, color = sport)) + 
  geom_point(data = res_grouped, aes(y = predestination_finish), color = "darkgray") + 
  geom_line(data = res_grouped, aes(y = predestination_finish), color = "darkgray") +
  geom_point(data = res_grouped, aes(y = parity_finish), color = "darkgray") + 
  geom_line(data = res_grouped, aes(y = parity_finish), color = "darkgray") +
  geom_point(data = res_grouped, aes(y = mean_finish)) + 
  geom_line(data = res_grouped, aes(y = mean_finish)) +
  geom_jitter(alpha = 0.007) + 
  geom_smooth() + 
  geom_text(data = labels, aes(label = label)) + 
  geom_text(data = labels2, aes(label = label), hjust = "left") + 
  geom_text(data = r_squared, x = 15, y = 1, 
            aes(label = paste("~R^2 =\n", round(r_squared, 3)))) + 
#  geom_curve(x = 15, y = 3.5, xend = 16, yend = 4.0625, arrow = arrow(length = unit(0.1, "cm"))) + 
  facet_wrap(~sport) + 
  ggtitle("Simulated 16-Team Tournaments, 2004-2016")
ggsave(filename = "../gfx/playoff_sims.pdf", width = 10, height = 8)
```

## How long should series be to equalize parity? 

```{r}
get_r_squared <- function(data) {
  res_grouped <- data %>%
    group_by(sport, num_teams, seed) %>%
    summarize(mean_finish = mean(finish)) %>%
    mutate(predestination_finish = ceiling(log2(seed)) + 1)

  parity <- res_grouped %>%
    summarize(parity_finish = mean(predestination_finish)) 

  res_grouped <- res_grouped %>%
    inner_join(parity, by = c("sport", "num_teams")) %>%
    mutate(SSM = (mean_finish - parity_finish)^2,
           SST = (predestination_finish - parity_finish)^2,
           weight = 17 - seed)

  r_squared <- res_grouped %>%
    group_by(sport, num_teams) %>%
    summarize(r_squared = sum(SSM) / sum(SST),
              weighted_r_squared = sum(weight * SSM) / sum(weight * SST))
  return(r_squared)
}

```

```{r}
sim_series <- function(data, n, series_length = 1) {
  data %>%
    group_by(sport, season, num_teams) %>%
    do(many_simulations(., n = n, series_length = series_length)) %>%
    get_r_squared() %>%
    mutate(series_length = series_length)
}
``` 

```{r}
sim_data8 <- bigfour_end %>%
  group_by(sport, season) %>%
  do(best_teams(., k = 8)) %>%
  mutate(num_teams = 8)

sim_data16 <- bigfour_end %>%
  group_by(sport, season) %>%
  do(best_teams(., k = 16)) %>%
  mutate(num_teams = 16)

sim_data <- sim_data16 %>%
  bind_rows(sim_data8)
```


```{r how_long, eval=TRUE}
# benchmark
series_lengths <- c(1, 3, 5, 7, 11, 15, 21, 35, 51, 75)
how_long <- lapply(series_lengths, sim_series, data = sim_data, n = 1000) %>% 
  bind_rows() %>%
  mutate(actual = case_when(
    sport == "nfl" & num_teams == 8 & series_length == 1 ~ TRUE,
    sport == "mlb" & num_teams == 8 & series_length == 7 ~ TRUE,
    sport %in% c("nba", "nhl") & num_teams == 16 & series_length == 7 ~ TRUE,
    TRUE ~ FALSE))
save(how_long, file = "../data/how_long.rda", compress = "xz")
```

```{r}
ggplot(how_long, aes(x = series_length, y = r_squared, color = sport)) + 
  geom_hline(yintercept = pull(filter(how_long, sport == "nba" & series_length == 7), r_squared), color = "darkgray", linetype = 2) + 
  geom_point(aes(size = actual, shape = factor(num_teams))) + 
#  geom_line() + 
  geom_smooth(se = FALSE, aes(linetype = factor(num_teams))) + 
  ggtitle("Equivalence of Playoff Series Length", 
          subtitle = "Simulated 8-Team and 16-Team Tournaments") + 
  scale_y_continuous("Pseudo-R^2") + 
  scale_x_continuous("Length of Series (each round)", breaks = series_lengths) + 
  scale_shape_discrete("teams") + scale_linetype_discrete("teams")
ggsave(filename = "../gfx/series_length.pdf", width = 10, height = 8)
```
