---
title: "SevenGameSeries"
author: "Michael Lopez"
date: "June 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("../config.R")
```

## Data wrangling

```{r, echo = TRUE}
library(ggbeeswarm)
library(RColorBrewer)
load(file.path(data_raw, "bigfour.rda"))
load(file.path(root, "data", "tidy_thetas.R1.rda"))
load(file.path(root, "data", "params.R1.rda"))
load(file.path(root, "data", "tidy_alphas.R1.rda"))

df.playoffs <- read.csv(file.path(root, "data", "playoff_rounds.csv"))
df.playoffs <- df.playoffs %>% mutate(season =  ifelse(sport == "nfl", season - 1, season))

sports <- c("nba", "nhl", "mlb", "nfl")
max.week <- data.frame(sport = sports, min.week = c(22, 25, 25, 14))
last.four.weeks <- tidy_thetas %>%
  mutate(season = season + 2005) %>% 
  left_join(max.week) %>% 
  filter(week > min.week) %>% 
  group_by(name, season, sport) %>% 
  summarise(theta.max = max(theta)) %>% 
  rename(theta = theta.max)

teamnames <- bigfour %>% 
  group_by(sport, home_team) %>% 
  summarise(n.games = n())
hfa <- select(params, sport, alpha)

table(df.playoffs$sport, df.playoffs$season)
tidy_alphas1 <- select(tidy_alphas, team, alpha.team.overall)
df.playoffs <- df.playoffs %>% 
  filter(! (sport == "nfl" & season == 2005))

df.playoffs1 <- df.playoffs %>% 
  left_join(last.four.weeks, by = c("Team1" = "name", "season" = "season", "sport" = "sport")) %>%
  rename(theta1 = theta) %>% 
  left_join(last.four.weeks, by = c("Team2" = "name", "season" = "season", "sport" = "sport")) %>% 
  rename(theta2 = theta) %>% 
  left_join(tidy_alphas1, by = c("Team1" = "team")) %>%
  rename(alpha1 = alpha.team.overall) %>% 
  left_join(tidy_alphas1, by = c("Team2" = "team")) %>%
  rename(alpha2 = alpha.team.overall)

df.playoffs2 <- df.playoffs1 %>% 
  filter(is.na(SeriesPrice)) %>% 
  mutate(better.first = theta1 > theta2, 
         team.b = ifelse(better.first, Team1, Team2), 
         team.w = ifelse(better.first, Team2, Team1), 
         theta.b = ifelse(better.first, theta1, theta2), 
         theta.w = ifelse(better.first, theta2, theta1), 
         alpha.b = ifelse(better.first, alpha1, alpha2), 
         alpha.w = ifelse(better.first, alpha2, alpha1)) %>%
  select(sport, season, team.b:alpha.w, Real, SeriesPrice) %>%
  mutate(prob.b.home = exp(alpha.b + theta.b - theta.w)/(1 + exp(alpha.b + theta.b - theta.w)), 
         prob.b.road = 1 - exp(alpha.w + theta.w - theta.b)/(1 + exp(alpha.w + theta.w - theta.b)), 
         prob.w.home = 1 - prob.b.home, 
         prob.w.road = 1 - prob.b.road)
df.playoffs.save <- df.playoffs2
```




## Series level probabilities

Here's a function to define the probability of the better team defeating the worse team in a seven game series

```{r, echo = TRUE}
games.out <- function(p1, p2, series.length){
  games.win <- ceiling(series.length/2)
  i <- 1
  win.series <- dbinom(1:games.win, games.win, p1)[games.win]*1
  for (i in 1:(games.win-1)){
    prob.temp <- dbinom(1:games.win, games.win, p1)[games.win-i]*(1-pbinom((i-1), (games.win-1), p2)) 
    win.series <- win.series + prob.temp
  }
  return(win.series)
}
```


Here we use that to define probabilities in our data

```{r, echo = TRUE}
df.playoffs2 <- df.playoffs2 %>% 
  group_by(1:n()) %>% 
  mutate(better.win.all = ifelse(sport == "nfl", prob.b.home, games.out(prob.b.home, prob.b.road, 7))) %>% 
  ungroup() %>% select(sport:team.w, better.win.all)

## Grab recent games
df.missing <- df.playoffs1 %>% filter(!is.na(SeriesPrice)) %>% select(sport, season, Team1, Team2, SeriesPrice) %>% 
  rename(team.b = Team1, team.w = Team2, better.win.all = SeriesPrice)

df.playoffs2 <- bind_rows(df.playoffs2, df.missing) %>% arrange(sport, -season)

```


## Graphs

```{r, echo = TRUE}

df.playoffs2$sport <- factor(df.playoffs2$sport)
levels(df.playoffs2$sport)<-c("mlb","nhl","nfl","nba")

ave.prob <- df.playoffs2 %>% 
  group_by(sport) %>% 
  summarise(ave.outcome = mean(better.win.all), med.outcome = median(better.win.all))

filter(df.playoffs2, season == 2016, sport == "mlb") %>% 
  select(sport, season, team.b, team.w, better.win.all) %>% 
  arrange(-better.win.all) %>% print.data.frame()


 

base_plot <- ggplot(df.playoffs2, aes(fill = toupper(sport), color = toupper(sport))) + 
  guides(fill = FALSE, color = FALSE, alpha = FALSE) + xlab("") + 
  scale_colour_brewer(palette = "Set2") +
  scale_alpha_continuous(range = c(0.25, 1))

```

```{r beeswarm}
gsw <- filter(df.playoffs2, team.b == "Golden State Warriors" & season == 2017)
wsh <- filter(df.playoffs2, team.b == "Washington Capitals" & season == 2017)
p<- base_plot + aes(x = factor(toupper(sport))) + 
  geom_hline(data = ave.prob, aes(yintercept = ave.outcome, color = toupper(sport)), 
             linetype = 2) + 
  geom_beeswarm(aes(y = better.win.all)) +
  ylab("Series win probability") + 
  geom_text(data = gsw, aes(label = team.w, y = better.win.all), nudge_x = -0.2, colour = "black") + 
  geom_curve(data = gsw, aes(y = better.win.all, xend = 4.5, yend = 0.9), 
             curvature = -0.3, 
             arrow = arrow(length = unit(0.2, "cm"), ends = "first", type = "closed")) + 
  annotate("text", x = 4.5, y = 0.9, label = "Golden State \n Warriors \n 2017") + 
  geom_text(data = wsh, aes(label = team.w, y = better.win.all), nudge_x = -0.2 , colour = "black") + 
  geom_curve(data = wsh, aes(y = better.win.all, xend = 2.5, yend = 0.7), 
             curvature = -0.3, 
             arrow = arrow(length = unit(0.2, "cm"), ends = "first", type = "closed")) +
  annotate("text", x = 2.5, y = 0.7, label = "Washington \n Capitals \n 2017") + 
  geom_beeswarm(data = gsw , aes(y = better.win.all) , colour = "black" , cex = 2) +
  geom_beeswarm(data = wsh , aes(y = better.win.all) , colour = "black" , cex = 2) + 
  xlab("League")
p

```

```{r plotly}
library(plotly)
gsw <- filter(df.playoffs2, team.b == "Golden State Warriors" & season == 2017)
wsh <- filter(df.playoffs2, team.b == "Washington Capitals" & season == 2017)
q<- base_plot + aes(x = factor(toupper(sport))) + 
  geom_hline(data = ave.prob, aes(yintercept = ave.outcome, color = toupper(sport)), 
             linetype = 2) + 
  geom_beeswarm(aes(y = better.win.all)) +
  ylab("Series win probability") + 
  # geom_text(data = gsw, aes(label = team.w, y = better.win.all), nudge_x = -0.2, colour = "black") + 
  # geom_curve(data = gsw, aes(y = better.win.all, xend = 4.5, yend = 0.9), 
  #            curvature = -0.3, 
  #            arrow = arrow(length = unit(0.2, "cm"), ends = "first", type = "closed")) + 
  # annotate("text", x = 4.5, y = 0.9, label = "Golden State \n Warriors \n 2017") + 
  # geom_text(data = wsh, aes(label = team.w, y = better.win.all), nudge_x = -0.2 , colour = "black") + 
  # geom_curve(data = wsh, aes(y = better.win.all, xend = 2.5, yend = 0.7), 
  #            curvature = -0.3, 
  #            arrow = arrow(length = unit(0.2, "cm"), ends = "first", type = "closed")) +
  # annotate("text", x = 2.5, y = 0.7, label = "Washington \n Capitals \n 2017") + 
  # geom_beeswarm(data = gsw , aes(y = better.win.all) , colour = "black" , cex = 2) +
  # geom_beeswarm(data = wsh , aes(y = better.win.all) , colour = "black" , cex = 2) + 
  xlab("League")
ggplotly(q,text=team.b)
```



```{r dots}
base_plot + aes(better.win.all, group = toupper(sport)) + 
  geom_dotplot(stackratio = .5) + 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) + 
  ylab("Percent of series") + 
  labs(title = "How often does the best team win in the postseason?", subtitle = "7 game series between all playoff teams, 2005-2016") +
  scale_x_continuous(labels = scales::percent) + 
  scale_y_continuous(labels = scales::percent) + 
  facet_wrap(~toupper(sport), ncol = 1)
```

```{r density}
base_plot + aes(better.win.all, group = toupper(sport)) + 
  geom_density(color = "black") + 
  geom_vline(data = ave.prob, aes(xintercept = ave.outcome), lty = 2) + 
  ylab("Percent of series") + 
  labs(title = "How often does the best team win in the postseason?", subtitle = "All playoff teams, 2005-2016 in 1 (NFL) or 7 game series") + 
  scale_x_continuous(labels=scales::percent) + 
  #scale_y_continuous(labels=scales::percent) + 
  facet_wrap(~toupper(sport), ncol = 1)
```

```{r histogram}
base_plot + aes(better.win.all) + 
  geom_histogram(aes(y = ..density..), color = "black") + 
  ylab("Series win probability") + 
  facet_wrap(~sport, ncol = 1)
```



## Extend to longer series

```{r, echo = TRUE}
df.playoffs3 <- df.playoffs.save %>% ungroup %>% group_by(1:n()) %>% mutate(prob.3 = games.out(prob.b.home, prob.b.road, 3), 
                                            prob.7 = games.out(prob.b.home, prob.b.road, 7), 
                                            prob.11 = games.out(prob.b.home, prob.b.road, 11),
                                            prob.21 = games.out(prob.b.home, prob.b.road, 21), 
                                            prob.41 = games.out(prob.b.home, prob.b.road, 41),
                                            prob.51 = games.out(prob.b.home, prob.b.road, 51), 
                                            prob.61 = games.out(prob.b.home, prob.b.road, 61), 
                                            prob.71 = games.out(prob.b.home, prob.b.road, 71),
                                            prob.81 = games.out(prob.b.home, prob.b.road, 81), 
                                            prob.91 = games.out(prob.b.home, prob.b.road, 91),
                                            prob.101 = games.out(prob.b.home, prob.b.road, 101))

df.playoffs3 %>% 
  ungroup() %>% 
  group_by(sport) %>% 
  summarise(prob.7 = mean(prob.7), 
            prob.41 = mean(prob.41),
            prob.51 = mean(prob.51), 
            prob.61 = mean(prob.61), 
            prob.91 = mean(prob.91), 
            prob.101 = mean(prob.101))
```
